@startuml
left to right direction
skinparam packageStyle rectangle

actor User
rectangle "WarunQ" {
    usecase Daftar
    usecase Masuk
    usecase "Point Of Sales" as POS
    usecase Pembukuan
}
User -- Daftar
User -- Masuk
User -- POS
User -- Pembukuan
@enduml
