/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.warunq.warunq;

import java.util.Arrays;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;

/**
 *
 * @author Win10
 */
public class DaftarFrame extends javax.swing.JFrame {

    /**
     * Creates new form DaftarFrame
     */
    public DaftarFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        daftarFrameLabel = new javax.swing.JLabel();
        namaAkunLabel = new javax.swing.JLabel();
        namaAkunField = new javax.swing.JTextField();
        kataSandiLabel = new javax.swing.JLabel();
        kataSandiField = new javax.swing.JPasswordField();
        konfirmasiLabel = new javax.swing.JLabel();
        konfirmasiField = new javax.swing.JPasswordField();
        daftarkanButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        masukButtonLabel = new javax.swing.JLabel();
        masukButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WarunQ - Daftar");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        daftarFrameLabel.setFont(new java.awt.Font("RobotoMono Nerd Font", 1, 24)); // NOI18N
        daftarFrameLabel.setText("Daftar");

        namaAkunLabel.setLabelFor(namaAkunField);
        namaAkunLabel.setText("Nama Akun");

        namaAkunField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaAkunFieldActionPerformed(evt);
            }
        });

        kataSandiLabel.setLabelFor(kataSandiField);
        kataSandiLabel.setText("Kata Sandi");

        kataSandiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kataSandiFieldActionPerformed(evt);
            }
        });

        konfirmasiLabel.setLabelFor(konfirmasiField);
        konfirmasiLabel.setText("Ketik Ulang Password :");

        daftarkanButton.setBackground(new java.awt.Color(244, 206, 20));
        daftarkanButton.setFont(new java.awt.Font("RobotoMono Nerd Font", 1, 12)); // NOI18N
        daftarkanButton.setText("Daftarkan");
        daftarkanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        daftarkanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarkanButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(244, 206, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        masukButtonLabel.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 10)); // NOI18N
        masukButtonLabel.setLabelFor(masukButton);
        masukButtonLabel.setText("Sudah Memiliki Akun?");

        masukButton.setFont(new java.awt.Font("RobotoMono Nerd Font", 1, 12)); // NOI18N
        masukButton.setText("Masuk");
        masukButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 206, 20), 1, true));
        masukButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(konfirmasiField)
                            .addComponent(kataSandiField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaAkunLabel)
                                    .addComponent(konfirmasiLabel)
                                    .addComponent(kataSandiLabel)
                                    .addComponent(daftarFrameLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(namaAkunField))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(daftarkanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(masukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(masukButtonLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(daftarFrameLabel)
                .addGap(18, 18, 18)
                .addComponent(namaAkunLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaAkunField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kataSandiLabel)
                .addGap(18, 18, 18)
                .addComponent(kataSandiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(konfirmasiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(konfirmasiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(daftarkanButton)
                .addGap(18, 18, 18)
                .addComponent(masukButtonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masukButton)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearForm() {
        namaAkunField.setText("");
        kataSandiField.setText("");
        konfirmasiField.setText("");
    }
    
    private void namaAkunFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaAkunFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaAkunFieldActionPerformed

    private void daftarkanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarkanButtonActionPerformed
        // TODO add your handling code here:
        String namaAkun = namaAkunField.getText();
        char[] kataSandi = kataSandiField.getPassword();
        char[] konfirmasi = konfirmasiField.getPassword();

        String querySQL = "SELECT `nama` FROM `akun` WHERE `nama` = '" + namaAkun + "'";

        if (namaAkun.isBlank() || kataSandi.length == 0 || konfirmasi.length == 0) {
            JOptionPane.showMessageDialog(null, "Silakan mengisi kolom nama akun dan kata sandi.");
        } else if (!Arrays.equals(kataSandi, konfirmasi)) {
            JOptionPane.showMessageDialog(null, "Kata sandi tidak sama. Periksa kembali kata sandi yang Anda ketik.");
            clearForm();
        }

        try {
            Connection connection = (Connection)db_koneksi.konfigurasi_koneksiDB();

            Statement statement = connection.createStatement();

            ResultSet resultSet = statement.executeQuery(querySQL);

            if (!resultSet.next()) {
                JOptionPane.showMessageDialog(null, "Akun berhasil didaftarkan!");
                MasukFrame masukFrame = new MasukFrame();
                masukFrame.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Nama akun sudah terpakai, pilih nama akun lain!");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal terhubung: " + e.getMessage());
        }

    }//GEN-LAST:event_daftarkanButtonActionPerformed

    private void kataSandiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kataSandiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kataSandiFieldActionPerformed

    private void masukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukButtonActionPerformed
        // TODO add your handling code here:
        MasukFrame masukFrame = new MasukFrame();
        masukFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_masukButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daftarFrameLabel;
    private javax.swing.JButton daftarkanButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField kataSandiField;
    private javax.swing.JLabel kataSandiLabel;
    private javax.swing.JPasswordField konfirmasiField;
    private javax.swing.JLabel konfirmasiLabel;
    private javax.swing.JButton masukButton;
    private javax.swing.JLabel masukButtonLabel;
    private javax.swing.JTextField namaAkunField;
    private javax.swing.JLabel namaAkunLabel;
    // End of variables declaration//GEN-END:variables
}
